# Generated by Django 5.0.7 on 2024-07-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('num_serie', models.IntegerField(primary_key=True, serialize=False)),
                ('num_inventaire', models.IntegerField()),
                ('cout', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('processeur', models.CharField(max_length=100)),
                ('disque_dur', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'materiel',
                'managed': False,
            },
        ),
    ]
