# Generated by Django 5.0.7 on 2024-07-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nom_utilisateur', models.CharField(max_length=100)),
                ('nom_service', models.CharField(max_length=100)),
                ('num_bureau', models.IntegerField()),
                ('intervention_demandee', models.CharField(max_length=2000)),
            ],
        ),
    ]
