# Generated by Django 5.0.7 on 2024-07-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GM', '0002_reclamation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamation',
            options={'managed': False},
        ),
    ]
