# Generated by Django 5.0.7 on 2024-07-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GM', '0003_alter_reclamation_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reclamation',
            table='reclamation',
        ),
    ]
