# Generated by Django 5.0.7 on 2024-07-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GM', '0004_alter_reclamation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_service', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
    ]
