# Generated by Django 5.0.7 on 2024-07-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GM', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id_Intervention', models.IntegerField(primary_key=True, serialize=False)),
                ('Descriptions', models.CharField(max_length=2000)),
                ('Matériel_objet', models.CharField(max_length=1000)),
                ('Matériel_réparé', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'Intervention',
                'managed': False,
            },
        ),
    ]
