# Generated by Django 5.0.7 on 2024-07-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GM', '0006_intervention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('num_bureau', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bureau',
                'managed': False,
            },
        ),
    ]
