# Generated by Django 5.0.7 on 2024-07-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GM', '0007_bureau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau_Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bureau_materiel',
                'managed': False,
            },
        ),
    ]
