# Generated by Django 5.0.7 on 2024-07-24 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GM', '0008_bureau_materiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('driver_license_number', models.CharField(max_length=20, null=True)),
                ('driver_license_front', models.ImageField(null=True, upload_to='licenses/front/')),
                ('driver_license_back', models.ImageField(null=True, upload_to='licenses/back/')),
                ('driver_license_expiration', models.DateField(null=True)),
                ('taxi_driver_license', models.ImageField(null=True, upload_to='taxi_licenses/')),
                ('photo', models.ImageField(null=True, upload_to='drivers/')),
                ('role', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='GM.role')),
            ],
        ),
    ]
