# Generated by Django 5.0.7 on 2024-07-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GM', '0009_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='driver_license_back',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_license_expiration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_license_front',
        ),
        migrations.RemoveField(
            model_name='user',
            name='driver_license_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='taxi_driver_license',
        ),
        migrations.AlterField(
            model_name='role',
            name='libelle',
            field=models.CharField(max_length=20),
        ),
    ]
